version: '2'
services:
  web:
    image: nginx
    ports:
      - "80:80"


    volumes:
      - ./conf:/etc/nginx/conf.d
    depends_on:
      - app

  app:
    image: iavorskiy/app_new:latest
    command: "gunicorn run:app --bind 0.0.0.0"



